package com.bishe.model;

import java.io.Serializable;

public class Blocked implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked.uid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked.by
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blocked
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked.id
     *
     * @return the value of blocked.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked.id
     *
     * @param id the value for blocked.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked.uid
     *
     * @return the value of blocked.uid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked.uid
     *
     * @param uid the value for blocked.uid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked.by
     *
     * @return the value of blocked.by
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getBy() {
        return by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked.by
     *
     * @param by the value for blocked.by
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setBy(Integer by) {
        this.by = by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", by=").append(by);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}