package com.bishe.model;

import java.io.Serializable;
import java.util.Date;

public class Chat implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.from
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.to
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.read
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.id
     *
     * @return the value of chat.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.id
     *
     * @param id the value for chat.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.from
     *
     * @return the value of chat.from
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.from
     *
     * @param from the value for chat.from
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setFrom(Integer from) {
        this.from = from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.to
     *
     * @return the value of chat.to
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.to
     *
     * @param to the value for chat.to
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTo(Integer to) {
        this.to = to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.read
     *
     * @return the value of chat.read
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.read
     *
     * @param read the value for chat.read
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setRead(Integer read) {
        this.read = read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.time
     *
     * @return the value of chat.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.time
     *
     * @param time the value for chat.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.message
     *
     * @return the value of chat.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.message
     *
     * @param message the value for chat.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", from=").append(from);
        sb.append(", to=").append(to);
        sb.append(", read=").append(read);
        sb.append(", time=").append(time);
        sb.append(", message=").append(message);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}