package com.bishe.model;

import java.io.Serializable;
import java.util.Date;

public class Comments implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.uid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.mid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer likes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comments
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.uid
     *
     * @return the value of comments.uid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.uid
     *
     * @param uid the value for comments.uid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.mid
     *
     * @return the value of comments.mid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.mid
     *
     * @param mid the value for comments.mid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.time
     *
     * @return the value of comments.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.time
     *
     * @param time the value for comments.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.likes
     *
     * @return the value of comments.likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.likes
     *
     * @param likes the value for comments.likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.message
     *
     * @return the value of comments.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.message
     *
     * @param message the value for comments.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", mid=").append(mid);
        sb.append(", time=").append(time);
        sb.append(", likes=").append(likes);
        sb.append(", message=").append(message);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}