package com.bishe.model;

import java.io.Serializable;
import java.util.Date;

public class Friendships implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendships.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendships.user1
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer user1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendships.user2
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer user2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendships.status
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendships.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friendships
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendships.id
     *
     * @return the value of friendships.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendships.id
     *
     * @param id the value for friendships.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendships.user1
     *
     * @return the value of friendships.user1
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getUser1() {
        return user1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendships.user1
     *
     * @param user1 the value for friendships.user1
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setUser1(Integer user1) {
        this.user1 = user1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendships.user2
     *
     * @return the value of friendships.user2
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getUser2() {
        return user2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendships.user2
     *
     * @param user2 the value for friendships.user2
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setUser2(Integer user2) {
        this.user2 = user2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendships.status
     *
     * @return the value of friendships.status
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendships.status
     *
     * @param status the value for friendships.status
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendships.time
     *
     * @return the value of friendships.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendships.time
     *
     * @param time the value for friendships.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendships
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", user1=").append(user1);
        sb.append(", user2=").append(user2);
        sb.append(", status=").append(status);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}