package com.bishe.model;

import java.io.Serializable;
import java.util.Date;

public class Groups implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.title
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.cover
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.privacy
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer privacy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.posts
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer posts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.description
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table groups
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.id
     *
     * @return the value of groups.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.id
     *
     * @param id the value for groups.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.name
     *
     * @return the value of groups.name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.name
     *
     * @param name the value for groups.name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.title
     *
     * @return the value of groups.title
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.title
     *
     * @param title the value for groups.title
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.cover
     *
     * @return the value of groups.cover
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.cover
     *
     * @param cover the value for groups.cover
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.privacy
     *
     * @return the value of groups.privacy
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getPrivacy() {
        return privacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.privacy
     *
     * @param privacy the value for groups.privacy
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPrivacy(Integer privacy) {
        this.privacy = privacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.posts
     *
     * @return the value of groups.posts
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getPosts() {
        return posts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.posts
     *
     * @param posts the value for groups.posts
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPosts(Integer posts) {
        this.posts = posts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.time
     *
     * @return the value of groups.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.time
     *
     * @param time the value for groups.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.description
     *
     * @return the value of groups.description
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.description
     *
     * @param description the value for groups.description
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", cover=").append(cover);
        sb.append(", privacy=").append(privacy);
        sb.append(", posts=").append(posts);
        sb.append(", time=").append(time);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}