package com.bishe.model;

import java.io.Serializable;
import java.util.Date;

public class Likes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.post
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.by
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.id
     *
     * @return the value of likes.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.id
     *
     * @param id the value for likes.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.post
     *
     * @return the value of likes.post
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.post
     *
     * @param post the value for likes.post
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPost(Integer post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.by
     *
     * @return the value of likes.by
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getBy() {
        return by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.by
     *
     * @param by the value for likes.by
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setBy(Integer by) {
        this.by = by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.type
     *
     * @return the value of likes.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.type
     *
     * @param type the value for likes.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.time
     *
     * @return the value of likes.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.time
     *
     * @param time the value for likes.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", post=").append(post);
        sb.append(", by=").append(by);
        sb.append(", type=").append(type);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}