package com.bishe.model;

import java.io.Serializable;
import java.util.Date;

public class Messages implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.uid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.tag
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.value
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.group
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.page
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.public_state
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer public_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer likes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.longitude
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.latitude
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.isPushed
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte isPushed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.id
     *
     * @return the value of messages.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.id
     *
     * @param id the value for messages.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.uid
     *
     * @return the value of messages.uid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.uid
     *
     * @param uid the value for messages.uid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.tag
     *
     * @return the value of messages.tag
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.tag
     *
     * @param tag the value for messages.tag
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.type
     *
     * @return the value of messages.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.type
     *
     * @param type the value for messages.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.value
     *
     * @return the value of messages.value
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.value
     *
     * @param value the value for messages.value
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.group
     *
     * @return the value of messages.group
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.group
     *
     * @param group the value for messages.group
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setGroup(Integer group) {
        this.group = group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.page
     *
     * @return the value of messages.page
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.page
     *
     * @param page the value for messages.page
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.time
     *
     * @return the value of messages.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.time
     *
     * @param time the value for messages.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.public_state
     *
     * @return the value of messages.public_state
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getPublic_state() {
        return public_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.public_state
     *
     * @param public_state the value for messages.public_state
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPublic_state(Integer public_state) {
        this.public_state = public_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.likes
     *
     * @return the value of messages.likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.likes
     *
     * @param likes the value for messages.likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.longitude
     *
     * @return the value of messages.longitude
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.longitude
     *
     * @param longitude the value for messages.longitude
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.latitude
     *
     * @return the value of messages.latitude
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.latitude
     *
     * @param latitude the value for messages.latitude
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.isPushed
     *
     * @return the value of messages.isPushed
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getIsPushed() {
        return isPushed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.isPushed
     *
     * @param isPushed the value for messages.isPushed
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setIsPushed(Byte isPushed) {
        this.isPushed = isPushed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.message
     *
     * @return the value of messages.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.message
     *
     * @param message the value for messages.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", tag=").append(tag);
        sb.append(", type=").append(type);
        sb.append(", value=").append(value);
        sb.append(", group=").append(group);
        sb.append(", page=").append(page);
        sb.append(", time=").append(time);
        sb.append(", public_state=").append(public_state);
        sb.append(", likes=").append(likes);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", isPushed=").append(isPushed);
        sb.append(", message=").append(message);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}