package com.bishe.model;

import java.io.Serializable;
import java.util.Date;

public class Notifications implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.from
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.to
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.parent
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.child
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer child;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.read
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.id
     *
     * @return the value of notifications.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.id
     *
     * @param id the value for notifications.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.from
     *
     * @return the value of notifications.from
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.from
     *
     * @param from the value for notifications.from
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setFrom(Integer from) {
        this.from = from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.to
     *
     * @return the value of notifications.to
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.to
     *
     * @param to the value for notifications.to
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTo(Integer to) {
        this.to = to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.parent
     *
     * @return the value of notifications.parent
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.parent
     *
     * @param parent the value for notifications.parent
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.child
     *
     * @return the value of notifications.child
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getChild() {
        return child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.child
     *
     * @param child the value for notifications.child
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setChild(Integer child) {
        this.child = child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.type
     *
     * @return the value of notifications.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.type
     *
     * @param type the value for notifications.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.read
     *
     * @return the value of notifications.read
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.read
     *
     * @param read the value for notifications.read
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setRead(Integer read) {
        this.read = read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.time
     *
     * @return the value of notifications.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.time
     *
     * @param time the value for notifications.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", from=").append(from);
        sb.append(", to=").append(to);
        sb.append(", parent=").append(parent);
        sb.append(", child=").append(child);
        sb.append(", type=").append(type);
        sb.append(", read=").append(read);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}