package com.bishe.model;

import java.io.Serializable;

public class Plugins implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plugins
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.id
     *
     * @return the value of plugins.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.id
     *
     * @param id the value for plugins.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.name
     *
     * @return the value of plugins.name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.name
     *
     * @param name the value for plugins.name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.type
     *
     * @return the value of plugins.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.type
     *
     * @param type the value for plugins.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}