package com.bishe.model;

import java.io.Serializable;
import java.util.Date;

public class Reports implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.post
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.parent
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.by
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.state
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reports.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reports
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.id
     *
     * @return the value of reports.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.id
     *
     * @param id the value for reports.id
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.post
     *
     * @return the value of reports.post
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.post
     *
     * @param post the value for reports.post
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.parent
     *
     * @return the value of reports.parent
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.parent
     *
     * @param parent the value for reports.parent
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.type
     *
     * @return the value of reports.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.type
     *
     * @param type the value for reports.type
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.by
     *
     * @return the value of reports.by
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getBy() {
        return by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.by
     *
     * @param by the value for reports.by
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setBy(Integer by) {
        this.by = by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.state
     *
     * @return the value of reports.state
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.state
     *
     * @param state the value for reports.state
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reports.time
     *
     * @return the value of reports.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reports.time
     *
     * @param time the value for reports.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", post=").append(post);
        sb.append(", parent=").append(parent);
        sb.append(", type=").append(type);
        sb.append(", by=").append(by);
        sb.append(", state=").append(state);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}