package com.bishe.model;

import java.io.Serializable;

public class Settings implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.title
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.theme
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.perpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer perpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.censor
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String censor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.captcha
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer captcha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.intervalm
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer intervalm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.intervaln
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer intervaln;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.size
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.format
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.mail
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.sizemsg
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer sizemsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.formatmsg
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String formatmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.cperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer cperpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.ilimit
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer ilimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.climit
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer climit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.uperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer uperpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.sperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer sperpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.nperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte nperpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.nperwidget
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte nperwidget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.lperpost
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer lperpost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.aperip
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer aperip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.conline
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer conline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.ronline
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte ronline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.mperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte mperpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.verified
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer verified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.chatr
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer chatr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.email_activation
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_activation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.email_comment
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.email_like
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_like;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.email_new_friend
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_new_friend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.email_group_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_group_invite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.email_page_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_page_invite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.smiles
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte smiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.fbapp
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer fbapp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.fbappid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String fbappid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.fbappsecret
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String fbappsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.smtp_email
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer smtp_email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.smtp_host
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String smtp_host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.smtp_port
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer smtp_port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.smtp_auth
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer smtp_auth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.smtp_username
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String smtp_username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.smtp_password
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String smtp_password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.ad1
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String ad1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.ad2
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String ad2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.ad3
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String ad3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.ad4
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String ad4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.ad5
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String ad5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.ad6
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String ad6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.ad7
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String ad7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settings.tracking_code
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String tracking_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table settings
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.title
     *
     * @return the value of settings.title
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.title
     *
     * @param title the value for settings.title
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.theme
     *
     * @return the value of settings.theme
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.theme
     *
     * @param theme the value for settings.theme
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.perpage
     *
     * @return the value of settings.perpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getPerpage() {
        return perpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.perpage
     *
     * @param perpage the value for settings.perpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPerpage(Integer perpage) {
        this.perpage = perpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.censor
     *
     * @return the value of settings.censor
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getCensor() {
        return censor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.censor
     *
     * @param censor the value for settings.censor
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setCensor(String censor) {
        this.censor = censor == null ? null : censor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.captcha
     *
     * @return the value of settings.captcha
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getCaptcha() {
        return captcha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.captcha
     *
     * @param captcha the value for settings.captcha
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setCaptcha(Integer captcha) {
        this.captcha = captcha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.intervalm
     *
     * @return the value of settings.intervalm
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getIntervalm() {
        return intervalm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.intervalm
     *
     * @param intervalm the value for settings.intervalm
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setIntervalm(Integer intervalm) {
        this.intervalm = intervalm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.intervaln
     *
     * @return the value of settings.intervaln
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getIntervaln() {
        return intervaln;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.intervaln
     *
     * @param intervaln the value for settings.intervaln
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setIntervaln(Integer intervaln) {
        this.intervaln = intervaln;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.time
     *
     * @return the value of settings.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.time
     *
     * @param time the value for settings.time
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.message
     *
     * @return the value of settings.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.message
     *
     * @param message the value for settings.message
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setMessage(Integer message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.size
     *
     * @return the value of settings.size
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.size
     *
     * @param size the value for settings.size
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.format
     *
     * @return the value of settings.format
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.format
     *
     * @param format the value for settings.format
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.mail
     *
     * @return the value of settings.mail
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.mail
     *
     * @param mail the value for settings.mail
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setMail(Integer mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.sizemsg
     *
     * @return the value of settings.sizemsg
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getSizemsg() {
        return sizemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.sizemsg
     *
     * @param sizemsg the value for settings.sizemsg
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSizemsg(Integer sizemsg) {
        this.sizemsg = sizemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.formatmsg
     *
     * @return the value of settings.formatmsg
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getFormatmsg() {
        return formatmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.formatmsg
     *
     * @param formatmsg the value for settings.formatmsg
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setFormatmsg(String formatmsg) {
        this.formatmsg = formatmsg == null ? null : formatmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.cperpage
     *
     * @return the value of settings.cperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getCperpage() {
        return cperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.cperpage
     *
     * @param cperpage the value for settings.cperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setCperpage(Integer cperpage) {
        this.cperpage = cperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.ilimit
     *
     * @return the value of settings.ilimit
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getIlimit() {
        return ilimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.ilimit
     *
     * @param ilimit the value for settings.ilimit
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setIlimit(Integer ilimit) {
        this.ilimit = ilimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.climit
     *
     * @return the value of settings.climit
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getClimit() {
        return climit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.climit
     *
     * @param climit the value for settings.climit
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setClimit(Integer climit) {
        this.climit = climit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.uperpage
     *
     * @return the value of settings.uperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getUperpage() {
        return uperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.uperpage
     *
     * @param uperpage the value for settings.uperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setUperpage(Integer uperpage) {
        this.uperpage = uperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.sperpage
     *
     * @return the value of settings.sperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getSperpage() {
        return sperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.sperpage
     *
     * @param sperpage the value for settings.sperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSperpage(Integer sperpage) {
        this.sperpage = sperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.nperpage
     *
     * @return the value of settings.nperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNperpage() {
        return nperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.nperpage
     *
     * @param nperpage the value for settings.nperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNperpage(Byte nperpage) {
        this.nperpage = nperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.nperwidget
     *
     * @return the value of settings.nperwidget
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNperwidget() {
        return nperwidget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.nperwidget
     *
     * @param nperwidget the value for settings.nperwidget
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNperwidget(Byte nperwidget) {
        this.nperwidget = nperwidget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.lperpost
     *
     * @return the value of settings.lperpost
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getLperpost() {
        return lperpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.lperpost
     *
     * @param lperpost the value for settings.lperpost
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setLperpost(Integer lperpost) {
        this.lperpost = lperpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.aperip
     *
     * @return the value of settings.aperip
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getAperip() {
        return aperip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.aperip
     *
     * @param aperip the value for settings.aperip
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setAperip(Integer aperip) {
        this.aperip = aperip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.conline
     *
     * @return the value of settings.conline
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getConline() {
        return conline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.conline
     *
     * @param conline the value for settings.conline
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setConline(Integer conline) {
        this.conline = conline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.ronline
     *
     * @return the value of settings.ronline
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getRonline() {
        return ronline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.ronline
     *
     * @param ronline the value for settings.ronline
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setRonline(Byte ronline) {
        this.ronline = ronline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.mperpage
     *
     * @return the value of settings.mperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getMperpage() {
        return mperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.mperpage
     *
     * @param mperpage the value for settings.mperpage
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setMperpage(Byte mperpage) {
        this.mperpage = mperpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.verified
     *
     * @return the value of settings.verified
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.verified
     *
     * @param verified the value for settings.verified
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setVerified(Integer verified) {
        this.verified = verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.chatr
     *
     * @return the value of settings.chatr
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getChatr() {
        return chatr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.chatr
     *
     * @param chatr the value for settings.chatr
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setChatr(Integer chatr) {
        this.chatr = chatr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.email_activation
     *
     * @return the value of settings.email_activation
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_activation() {
        return email_activation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.email_activation
     *
     * @param email_activation the value for settings.email_activation
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_activation(Byte email_activation) {
        this.email_activation = email_activation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.email_comment
     *
     * @return the value of settings.email_comment
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_comment() {
        return email_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.email_comment
     *
     * @param email_comment the value for settings.email_comment
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_comment(Byte email_comment) {
        this.email_comment = email_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.email_like
     *
     * @return the value of settings.email_like
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_like() {
        return email_like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.email_like
     *
     * @param email_like the value for settings.email_like
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_like(Byte email_like) {
        this.email_like = email_like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.email_new_friend
     *
     * @return the value of settings.email_new_friend
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_new_friend() {
        return email_new_friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.email_new_friend
     *
     * @param email_new_friend the value for settings.email_new_friend
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_new_friend(Byte email_new_friend) {
        this.email_new_friend = email_new_friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.email_group_invite
     *
     * @return the value of settings.email_group_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_group_invite() {
        return email_group_invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.email_group_invite
     *
     * @param email_group_invite the value for settings.email_group_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_group_invite(Byte email_group_invite) {
        this.email_group_invite = email_group_invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.email_page_invite
     *
     * @return the value of settings.email_page_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_page_invite() {
        return email_page_invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.email_page_invite
     *
     * @param email_page_invite the value for settings.email_page_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_page_invite(Byte email_page_invite) {
        this.email_page_invite = email_page_invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.smiles
     *
     * @return the value of settings.smiles
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getSmiles() {
        return smiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.smiles
     *
     * @param smiles the value for settings.smiles
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSmiles(Byte smiles) {
        this.smiles = smiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.fbapp
     *
     * @return the value of settings.fbapp
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getFbapp() {
        return fbapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.fbapp
     *
     * @param fbapp the value for settings.fbapp
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setFbapp(Integer fbapp) {
        this.fbapp = fbapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.fbappid
     *
     * @return the value of settings.fbappid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getFbappid() {
        return fbappid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.fbappid
     *
     * @param fbappid the value for settings.fbappid
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setFbappid(String fbappid) {
        this.fbappid = fbappid == null ? null : fbappid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.fbappsecret
     *
     * @return the value of settings.fbappsecret
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getFbappsecret() {
        return fbappsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.fbappsecret
     *
     * @param fbappsecret the value for settings.fbappsecret
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setFbappsecret(String fbappsecret) {
        this.fbappsecret = fbappsecret == null ? null : fbappsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.smtp_email
     *
     * @return the value of settings.smtp_email
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getSmtp_email() {
        return smtp_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.smtp_email
     *
     * @param smtp_email the value for settings.smtp_email
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSmtp_email(Integer smtp_email) {
        this.smtp_email = smtp_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.smtp_host
     *
     * @return the value of settings.smtp_host
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getSmtp_host() {
        return smtp_host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.smtp_host
     *
     * @param smtp_host the value for settings.smtp_host
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSmtp_host(String smtp_host) {
        this.smtp_host = smtp_host == null ? null : smtp_host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.smtp_port
     *
     * @return the value of settings.smtp_port
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getSmtp_port() {
        return smtp_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.smtp_port
     *
     * @param smtp_port the value for settings.smtp_port
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSmtp_port(Integer smtp_port) {
        this.smtp_port = smtp_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.smtp_auth
     *
     * @return the value of settings.smtp_auth
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getSmtp_auth() {
        return smtp_auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.smtp_auth
     *
     * @param smtp_auth the value for settings.smtp_auth
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSmtp_auth(Integer smtp_auth) {
        this.smtp_auth = smtp_auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.smtp_username
     *
     * @return the value of settings.smtp_username
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getSmtp_username() {
        return smtp_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.smtp_username
     *
     * @param smtp_username the value for settings.smtp_username
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSmtp_username(String smtp_username) {
        this.smtp_username = smtp_username == null ? null : smtp_username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.smtp_password
     *
     * @return the value of settings.smtp_password
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getSmtp_password() {
        return smtp_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.smtp_password
     *
     * @param smtp_password the value for settings.smtp_password
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSmtp_password(String smtp_password) {
        this.smtp_password = smtp_password == null ? null : smtp_password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.ad1
     *
     * @return the value of settings.ad1
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getAd1() {
        return ad1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.ad1
     *
     * @param ad1 the value for settings.ad1
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setAd1(String ad1) {
        this.ad1 = ad1 == null ? null : ad1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.ad2
     *
     * @return the value of settings.ad2
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getAd2() {
        return ad2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.ad2
     *
     * @param ad2 the value for settings.ad2
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setAd2(String ad2) {
        this.ad2 = ad2 == null ? null : ad2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.ad3
     *
     * @return the value of settings.ad3
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getAd3() {
        return ad3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.ad3
     *
     * @param ad3 the value for settings.ad3
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setAd3(String ad3) {
        this.ad3 = ad3 == null ? null : ad3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.ad4
     *
     * @return the value of settings.ad4
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getAd4() {
        return ad4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.ad4
     *
     * @param ad4 the value for settings.ad4
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setAd4(String ad4) {
        this.ad4 = ad4 == null ? null : ad4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.ad5
     *
     * @return the value of settings.ad5
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getAd5() {
        return ad5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.ad5
     *
     * @param ad5 the value for settings.ad5
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setAd5(String ad5) {
        this.ad5 = ad5 == null ? null : ad5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.ad6
     *
     * @return the value of settings.ad6
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getAd6() {
        return ad6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.ad6
     *
     * @param ad6 the value for settings.ad6
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setAd6(String ad6) {
        this.ad6 = ad6 == null ? null : ad6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.ad7
     *
     * @return the value of settings.ad7
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getAd7() {
        return ad7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.ad7
     *
     * @param ad7 the value for settings.ad7
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setAd7(String ad7) {
        this.ad7 = ad7 == null ? null : ad7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settings.tracking_code
     *
     * @return the value of settings.tracking_code
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getTracking_code() {
        return tracking_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settings.tracking_code
     *
     * @param tracking_code the value for settings.tracking_code
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTracking_code(String tracking_code) {
        this.tracking_code = tracking_code == null ? null : tracking_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settings
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", title=").append(title);
        sb.append(", theme=").append(theme);
        sb.append(", perpage=").append(perpage);
        sb.append(", censor=").append(censor);
        sb.append(", captcha=").append(captcha);
        sb.append(", intervalm=").append(intervalm);
        sb.append(", intervaln=").append(intervaln);
        sb.append(", time=").append(time);
        sb.append(", message=").append(message);
        sb.append(", size=").append(size);
        sb.append(", format=").append(format);
        sb.append(", mail=").append(mail);
        sb.append(", sizemsg=").append(sizemsg);
        sb.append(", formatmsg=").append(formatmsg);
        sb.append(", cperpage=").append(cperpage);
        sb.append(", ilimit=").append(ilimit);
        sb.append(", climit=").append(climit);
        sb.append(", uperpage=").append(uperpage);
        sb.append(", sperpage=").append(sperpage);
        sb.append(", nperpage=").append(nperpage);
        sb.append(", nperwidget=").append(nperwidget);
        sb.append(", lperpost=").append(lperpost);
        sb.append(", aperip=").append(aperip);
        sb.append(", conline=").append(conline);
        sb.append(", ronline=").append(ronline);
        sb.append(", mperpage=").append(mperpage);
        sb.append(", verified=").append(verified);
        sb.append(", chatr=").append(chatr);
        sb.append(", email_activation=").append(email_activation);
        sb.append(", email_comment=").append(email_comment);
        sb.append(", email_like=").append(email_like);
        sb.append(", email_new_friend=").append(email_new_friend);
        sb.append(", email_group_invite=").append(email_group_invite);
        sb.append(", email_page_invite=").append(email_page_invite);
        sb.append(", smiles=").append(smiles);
        sb.append(", fbapp=").append(fbapp);
        sb.append(", fbappid=").append(fbappid);
        sb.append(", fbappsecret=").append(fbappsecret);
        sb.append(", smtp_email=").append(smtp_email);
        sb.append(", smtp_host=").append(smtp_host);
        sb.append(", smtp_port=").append(smtp_port);
        sb.append(", smtp_auth=").append(smtp_auth);
        sb.append(", smtp_username=").append(smtp_username);
        sb.append(", smtp_password=").append(smtp_password);
        sb.append(", ad1=").append(ad1);
        sb.append(", ad2=").append(ad2);
        sb.append(", ad3=").append(ad3);
        sb.append(", ad4=").append(ad4);
        sb.append(", ad5=").append(ad5);
        sb.append(", ad6=").append(ad6);
        sb.append(", ad7=").append(ad7);
        sb.append(", tracking_code=").append(tracking_code);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}