package com.bishe.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.idu
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer idu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.first_name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String first_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String last_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.country
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.location
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.work
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String work;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.school
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.website
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bio
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String bio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.date
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.facebook
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String facebook;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.twitter
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String twitter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gplus
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String gplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.image
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.private_states
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer private_states;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.suspended
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer suspended;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salted
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String salted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cover
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.verified
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer verified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.privacy
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer privacy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.interests
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte interests;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.online
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.offline
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte offline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ip
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_group
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Integer user_group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notificationl
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte notificationl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notificationc
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte notificationc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte notifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notificationd
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte notificationd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notificationf
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte notificationf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notificationg
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte notificationg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notificationx
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte notificationx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.notificationp
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte notificationp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_comment
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_like
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_like;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_new_friend
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_new_friend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_group_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_group_invite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_page_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte email_page_invite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sound_new_notification
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte sound_new_notification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sound_new_chat
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte sound_new_chat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.born
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Date born;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastloginlat
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Double lastloginlat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastloginlong
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Double lastloginlong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.push
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private Byte push;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.idu
     *
     * @return the value of user.idu
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getIdu() {
        return idu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.idu
     *
     * @param idu the value for user.idu
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setIdu(Integer idu) {
        this.idu = idu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.first_name
     *
     * @return the value of user.first_name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getFirst_name() {
        return first_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.first_name
     *
     * @param first_name the value for user.first_name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setFirst_name(String first_name) {
        this.first_name = first_name == null ? null : first_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_name
     *
     * @return the value of user.last_name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getLast_name() {
        return last_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_name
     *
     * @param last_name the value for user.last_name
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setLast_name(String last_name) {
        this.last_name = last_name == null ? null : last_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.country
     *
     * @return the value of user.country
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.country
     *
     * @param country the value for user.country
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.location
     *
     * @return the value of user.location
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.location
     *
     * @param location the value for user.location
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.work
     *
     * @return the value of user.work
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.work
     *
     * @param work the value for user.work
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setWork(String work) {
        this.work = work == null ? null : work.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.school
     *
     * @return the value of user.school
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.school
     *
     * @param school the value for user.school
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.website
     *
     * @return the value of user.website
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.website
     *
     * @param website the value for user.website
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bio
     *
     * @return the value of user.bio
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bio
     *
     * @param bio the value for user.bio
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.date
     *
     * @return the value of user.date
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.date
     *
     * @param date the value for user.date
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.facebook
     *
     * @return the value of user.facebook
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getFacebook() {
        return facebook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.facebook
     *
     * @param facebook the value for user.facebook
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setFacebook(String facebook) {
        this.facebook = facebook == null ? null : facebook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.twitter
     *
     * @return the value of user.twitter
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getTwitter() {
        return twitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.twitter
     *
     * @param twitter the value for user.twitter
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setTwitter(String twitter) {
        this.twitter = twitter == null ? null : twitter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gplus
     *
     * @return the value of user.gplus
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getGplus() {
        return gplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gplus
     *
     * @param gplus the value for user.gplus
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setGplus(String gplus) {
        this.gplus = gplus == null ? null : gplus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.image
     *
     * @return the value of user.image
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.image
     *
     * @param image the value for user.image
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.private_states
     *
     * @return the value of user.private_states
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getPrivate_states() {
        return private_states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.private_states
     *
     * @param private_states the value for user.private_states
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPrivate_states(Integer private_states) {
        this.private_states = private_states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.suspended
     *
     * @return the value of user.suspended
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getSuspended() {
        return suspended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.suspended
     *
     * @param suspended the value for user.suspended
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSuspended(Integer suspended) {
        this.suspended = suspended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.salted
     *
     * @return the value of user.salted
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getSalted() {
        return salted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.salted
     *
     * @param salted the value for user.salted
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSalted(String salted) {
        this.salted = salted == null ? null : salted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cover
     *
     * @return the value of user.cover
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cover
     *
     * @param cover the value for user.cover
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.verified
     *
     * @return the value of user.verified
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.verified
     *
     * @param verified the value for user.verified
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setVerified(Integer verified) {
        this.verified = verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.privacy
     *
     * @return the value of user.privacy
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getPrivacy() {
        return privacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.privacy
     *
     * @param privacy the value for user.privacy
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPrivacy(Integer privacy) {
        this.privacy = privacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.interests
     *
     * @return the value of user.interests
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getInterests() {
        return interests;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.interests
     *
     * @param interests the value for user.interests
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setInterests(Byte interests) {
        this.interests = interests;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.online
     *
     * @return the value of user.online
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.online
     *
     * @param online the value for user.online
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setOnline(Integer online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.offline
     *
     * @return the value of user.offline
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getOffline() {
        return offline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.offline
     *
     * @param offline the value for user.offline
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setOffline(Byte offline) {
        this.offline = offline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ip
     *
     * @return the value of user.ip
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ip
     *
     * @param ip the value for user.ip
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_group
     *
     * @return the value of user.user_group
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Integer getUser_group() {
        return user_group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_group
     *
     * @param user_group the value for user.user_group
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setUser_group(Integer user_group) {
        this.user_group = user_group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notificationl
     *
     * @return the value of user.notificationl
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNotificationl() {
        return notificationl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notificationl
     *
     * @param notificationl the value for user.notificationl
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNotificationl(Byte notificationl) {
        this.notificationl = notificationl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notificationc
     *
     * @return the value of user.notificationc
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNotificationc() {
        return notificationc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notificationc
     *
     * @param notificationc the value for user.notificationc
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNotificationc(Byte notificationc) {
        this.notificationc = notificationc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notifications
     *
     * @return the value of user.notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNotifications() {
        return notifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notifications
     *
     * @param notifications the value for user.notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNotifications(Byte notifications) {
        this.notifications = notifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notificationd
     *
     * @return the value of user.notificationd
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNotificationd() {
        return notificationd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notificationd
     *
     * @param notificationd the value for user.notificationd
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNotificationd(Byte notificationd) {
        this.notificationd = notificationd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notificationf
     *
     * @return the value of user.notificationf
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNotificationf() {
        return notificationf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notificationf
     *
     * @param notificationf the value for user.notificationf
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNotificationf(Byte notificationf) {
        this.notificationf = notificationf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notificationg
     *
     * @return the value of user.notificationg
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNotificationg() {
        return notificationg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notificationg
     *
     * @param notificationg the value for user.notificationg
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNotificationg(Byte notificationg) {
        this.notificationg = notificationg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notificationx
     *
     * @return the value of user.notificationx
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNotificationx() {
        return notificationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notificationx
     *
     * @param notificationx the value for user.notificationx
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNotificationx(Byte notificationx) {
        this.notificationx = notificationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.notificationp
     *
     * @return the value of user.notificationp
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getNotificationp() {
        return notificationp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.notificationp
     *
     * @param notificationp the value for user.notificationp
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setNotificationp(Byte notificationp) {
        this.notificationp = notificationp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_comment
     *
     * @return the value of user.email_comment
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_comment() {
        return email_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_comment
     *
     * @param email_comment the value for user.email_comment
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_comment(Byte email_comment) {
        this.email_comment = email_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_like
     *
     * @return the value of user.email_like
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_like() {
        return email_like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_like
     *
     * @param email_like the value for user.email_like
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_like(Byte email_like) {
        this.email_like = email_like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_new_friend
     *
     * @return the value of user.email_new_friend
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_new_friend() {
        return email_new_friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_new_friend
     *
     * @param email_new_friend the value for user.email_new_friend
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_new_friend(Byte email_new_friend) {
        this.email_new_friend = email_new_friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_group_invite
     *
     * @return the value of user.email_group_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_group_invite() {
        return email_group_invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_group_invite
     *
     * @param email_group_invite the value for user.email_group_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_group_invite(Byte email_group_invite) {
        this.email_group_invite = email_group_invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_page_invite
     *
     * @return the value of user.email_page_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getEmail_page_invite() {
        return email_page_invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_page_invite
     *
     * @param email_page_invite the value for user.email_page_invite
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setEmail_page_invite(Byte email_page_invite) {
        this.email_page_invite = email_page_invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sound_new_notification
     *
     * @return the value of user.sound_new_notification
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getSound_new_notification() {
        return sound_new_notification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sound_new_notification
     *
     * @param sound_new_notification the value for user.sound_new_notification
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSound_new_notification(Byte sound_new_notification) {
        this.sound_new_notification = sound_new_notification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sound_new_chat
     *
     * @return the value of user.sound_new_chat
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getSound_new_chat() {
        return sound_new_chat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sound_new_chat
     *
     * @param sound_new_chat the value for user.sound_new_chat
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setSound_new_chat(Byte sound_new_chat) {
        this.sound_new_chat = sound_new_chat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.born
     *
     * @return the value of user.born
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Date getBorn() {
        return born;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.born
     *
     * @param born the value for user.born
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setBorn(Date born) {
        this.born = born;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastloginlat
     *
     * @return the value of user.lastloginlat
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Double getLastloginlat() {
        return lastloginlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastloginlat
     *
     * @param lastloginlat the value for user.lastloginlat
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setLastloginlat(Double lastloginlat) {
        this.lastloginlat = lastloginlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastloginlong
     *
     * @return the value of user.lastloginlong
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Double getLastloginlong() {
        return lastloginlong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastloginlong
     *
     * @param lastloginlong the value for user.lastloginlong
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setLastloginlong(Double lastloginlong) {
        this.lastloginlong = lastloginlong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.push
     *
     * @return the value of user.push
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public Byte getPush() {
        return push;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.push
     *
     * @param push the value for user.push
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    public void setPush(Byte push) {
        this.push = push;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idu=").append(idu);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", first_name=").append(first_name);
        sb.append(", last_name=").append(last_name);
        sb.append(", country=").append(country);
        sb.append(", location=").append(location);
        sb.append(", address=").append(address);
        sb.append(", work=").append(work);
        sb.append(", school=").append(school);
        sb.append(", website=").append(website);
        sb.append(", bio=").append(bio);
        sb.append(", date=").append(date);
        sb.append(", facebook=").append(facebook);
        sb.append(", twitter=").append(twitter);
        sb.append(", gplus=").append(gplus);
        sb.append(", image=").append(image);
        sb.append(", private_states=").append(private_states);
        sb.append(", suspended=").append(suspended);
        sb.append(", salted=").append(salted);
        sb.append(", cover=").append(cover);
        sb.append(", verified=").append(verified);
        sb.append(", privacy=").append(privacy);
        sb.append(", gender=").append(gender);
        sb.append(", interests=").append(interests);
        sb.append(", online=").append(online);
        sb.append(", offline=").append(offline);
        sb.append(", ip=").append(ip);
        sb.append(", user_group=").append(user_group);
        sb.append(", notificationl=").append(notificationl);
        sb.append(", notificationc=").append(notificationc);
        sb.append(", notifications=").append(notifications);
        sb.append(", notificationd=").append(notificationd);
        sb.append(", notificationf=").append(notificationf);
        sb.append(", notificationg=").append(notificationg);
        sb.append(", notificationx=").append(notificationx);
        sb.append(", notificationp=").append(notificationp);
        sb.append(", email_comment=").append(email_comment);
        sb.append(", email_like=").append(email_like);
        sb.append(", email_new_friend=").append(email_new_friend);
        sb.append(", email_group_invite=").append(email_group_invite);
        sb.append(", email_page_invite=").append(email_page_invite);
        sb.append(", sound_new_notification=").append(sound_new_notification);
        sb.append(", sound_new_chat=").append(sound_new_chat);
        sb.append(", born=").append(born);
        sb.append(", lastloginlat=").append(lastloginlat);
        sb.append(", lastloginlong=").append(lastloginlong);
        sb.append(", push=").append(push);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}