package com.bishe.dao;

import com.bishe.model.Blocked;
import java.util.List;

public interface BlockedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Blocked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    Blocked selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Blocked> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int updateByPrimaryKey(Blocked record);
}