package com.bishe.dao;

import com.bishe.model.Friendships;
import java.util.List;

public interface FriendshipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendships
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendships
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Friendships record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendships
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    Friendships selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendships
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Friendships> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendships
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int updateByPrimaryKey(Friendships record);
}