package com.bishe.dao;

import com.bishe.model.Groups;
import java.util.List;

public interface GroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Groups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    Groups selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Groups> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int updateByPrimaryKey(Groups record);
}