package com.bishe.dao;

import com.bishe.model.Likes;
import java.util.List;

public interface LikesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Likes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    Likes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Likes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int updateByPrimaryKey(Likes record);
}