package com.bishe.dao;

import com.bishe.model.Messages;
import com.bishe.tmp.UserMessage;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    Messages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Messages> selectAll();

    List<Messages> getMessageList(int offset,int limit,int userId);
    List<UserMessage> getUserMessageList(int offset, int limit, int userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int updateByPrimaryKey(Messages record);
}