package com.bishe.dao;

import com.bishe.model.Notifications;
import java.util.List;

public interface NotificationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Notifications record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    Notifications selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Notifications> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int updateByPrimaryKey(Notifications record);
}