package com.bishe.dao;

import com.bishe.model.Pages;
import java.util.List;

public interface PagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Pages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    Pages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Pages> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int updateByPrimaryKey(Pages record);
}