package com.bishe.dao;

import com.bishe.model.Plugins;
import java.util.List;

public interface PluginsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Plugins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    Plugins selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Plugins> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugins
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int updateByPrimaryKey(Plugins record);
}