package com.bishe.dao;

import com.bishe.model.Reports;
import java.util.List;

public interface ReportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Reports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    Reports selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Reports> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int updateByPrimaryKey(Reports record);
}