package com.bishe.dao;

import com.bishe.model.Settings;
import java.util.List;

public interface SettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settings
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    int insert(Settings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settings
     *
     * @mbggenerated Sun Apr 07 18:38:05 CST 2019
     */
    List<Settings> selectAll();
}